// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package psadm is a generated GoMock package.
package psadm

import (
	reflect "reflect"
	time "time"

	ssm "github.com/aws/aws-sdk-go/service/ssm"
	gomock "github.com/golang/mock/gomock"
)

// MockssmClient is a mock of ssmClient interface.
type MockssmClient struct {
	ctrl     *gomock.Controller
	recorder *MockssmClientMockRecorder
}

// MockssmClientMockRecorder is the mock recorder for MockssmClient.
type MockssmClientMockRecorder struct {
	mock *MockssmClient
}

// NewMockssmClient creates a new mock instance.
func NewMockssmClient(ctrl *gomock.Controller) *MockssmClient {
	mock := &MockssmClient{ctrl: ctrl}
	mock.recorder = &MockssmClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockssmClient) EXPECT() *MockssmClientMockRecorder {
	return m.recorder
}

// DescribeParameters mocks base method.
func (m *MockssmClient) DescribeParameters(arg0 *ssm.DescribeParametersInput) (*ssm.DescribeParametersOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeParameters", arg0)
	ret0, _ := ret[0].(*ssm.DescribeParametersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeParameters indicates an expected call of DescribeParameters.
func (mr *MockssmClientMockRecorder) DescribeParameters(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeParameters", reflect.TypeOf((*MockssmClient)(nil).DescribeParameters), arg0)
}

// GetParameter mocks base method.
func (m *MockssmClient) GetParameter(arg0 *ssm.GetParameterInput) (*ssm.GetParameterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParameter", arg0)
	ret0, _ := ret[0].(*ssm.GetParameterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParameter indicates an expected call of GetParameter.
func (mr *MockssmClientMockRecorder) GetParameter(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParameter", reflect.TypeOf((*MockssmClient)(nil).GetParameter), arg0)
}

// GetParameterHistory mocks base method.
func (m *MockssmClient) GetParameterHistory(arg0 *ssm.GetParameterHistoryInput) (*ssm.GetParameterHistoryOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParameterHistory", arg0)
	ret0, _ := ret[0].(*ssm.GetParameterHistoryOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParameterHistory indicates an expected call of GetParameterHistory.
func (mr *MockssmClientMockRecorder) GetParameterHistory(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParameterHistory", reflect.TypeOf((*MockssmClient)(nil).GetParameterHistory), arg0)
}

// PutParameter mocks base method.
func (m *MockssmClient) PutParameter(arg0 *ssm.PutParameterInput) (*ssm.PutParameterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutParameter", arg0)
	ret0, _ := ret[0].(*ssm.PutParameterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutParameter indicates an expected call of PutParameter.
func (mr *MockssmClientMockRecorder) PutParameter(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutParameter", reflect.TypeOf((*MockssmClient)(nil).PutParameter), arg0)
}

// Mockclient is a mock of client interface.
type Mockclient struct {
	ctrl     *gomock.Controller
	recorder *MockclientMockRecorder
}

// MockclientMockRecorder is the mock recorder for Mockclient.
type MockclientMockRecorder struct {
	mock *Mockclient
}

// NewMockclient creates a new mock instance.
func NewMockclient(ctrl *gomock.Controller) *Mockclient {
	mock := &Mockclient{ctrl: ctrl}
	mock.recorder = &MockclientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockclient) EXPECT() *MockclientMockRecorder {
	return m.recorder
}

// GetParameter mocks base method.
func (m *Mockclient) GetParameter(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParameter", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParameter indicates an expected call of GetParameter.
func (mr *MockclientMockRecorder) GetParameter(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParameter", reflect.TypeOf((*Mockclient)(nil).GetParameter), arg0)
}

// GetParameterByTime mocks base method.
func (m *Mockclient) GetParameterByTime(arg0 string, arg1 time.Time) (*Parameter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParameterByTime", arg0, arg1)
	ret0, _ := ret[0].(*Parameter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParameterByTime indicates an expected call of GetParameterByTime.
func (mr *MockclientMockRecorder) GetParameterByTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParameterByTime", reflect.TypeOf((*Mockclient)(nil).GetParameterByTime), arg0, arg1)
}

// GetParameterWithDescription mocks base method.
func (m *Mockclient) GetParameterWithDescription(arg0 string) (*Parameter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParameterWithDescription", arg0)
	ret0, _ := ret[0].(*Parameter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParameterWithDescription indicates an expected call of GetParameterWithDescription.
func (mr *MockclientMockRecorder) GetParameterWithDescription(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParameterWithDescription", reflect.TypeOf((*Mockclient)(nil).GetParameterWithDescription), arg0)
}

// GetParametersByPath mocks base method.
func (m *Mockclient) GetParametersByPath(arg0 string) ([]*Parameter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParametersByPath", arg0)
	ret0, _ := ret[0].([]*Parameter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParametersByPath indicates an expected call of GetParametersByPath.
func (mr *MockclientMockRecorder) GetParametersByPath(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParametersByPath", reflect.TypeOf((*Mockclient)(nil).GetParametersByPath), arg0)
}

// PutParameter mocks base method.
func (m *Mockclient) PutParameter(arg0 *Parameter, arg1 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutParameter", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutParameter indicates an expected call of PutParameter.
func (mr *MockclientMockRecorder) PutParameter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutParameter", reflect.TypeOf((*Mockclient)(nil).PutParameter), arg0, arg1)
}
